category_counts: '[369]'
column_definition: '[(''id'', <DataTypes.REAL_VALUED: 0>, <InputTypes.ID: 4>), (''hours_from_start'',
  <DataTypes.REAL_VALUED: 0>, <InputTypes.TIME: 5>), (''power_usage'', <DataTypes.REAL_VALUED:
  0>, <InputTypes.TARGET: 0>), (''hour'', <DataTypes.REAL_VALUED: 0>, <InputTypes.KNOWN_INPUT:
  2>), (''day_of_week'', <DataTypes.REAL_VALUED: 0>, <InputTypes.KNOWN_INPUT: 2>),
  (''hours_from_start'', <DataTypes.REAL_VALUED: 0>, <InputTypes.KNOWN_INPUT: 2>),
  (''categorical_id'', <DataTypes.CATEGORICAL: 1>, <InputTypes.STATIC_INPUT: 3>)]'
dropout_rate: 0.1
early_stopping_patience: 5
hidden_layer_size: 160
input_obs_loc: '[0]'
input_size: 5
known_categorical_inputs: '[0]'
known_regular_inputs: '[1, 2, 3]'
learning_rate: 0.001
max_gradient_norm: 0.01
minibatch_size: 64
multiprocessing_workers: 5
num_encoder_steps: 168
num_epochs: 1
num_heads: 4
output_size: 1
stack_size: 1
static_input_loc: '[4]'
total_time_steps: 192
